#!/usr/bin/env bash
export VENV_DIR=.pyenv

install_basic_packages() {
    echo "========================================== Install basic packages ==========================================="
    packages="software-properties-common git git-lfs kubectl jq"
    echo $packages | xargs sudo dpkg -s &> /dev/null
    if [ $? != 0 ]; then
        sudo apt-get -q update
        sudo apt-get -qy install $packages
        git lfs install 
    else
        echo "Already installed."
    fi
}

setup_venv() {
    echo "=========================================== Install & setup venv ============================================"
    if [ ! -d $VENV_DIR ]; then
        echo "Create python venv"
        python3 -m virtualenv $VENV_DIR
    fi
    echo "Activate python venv"
    source $VENV_DIR/bin/activate
    pip install -q -r requirements.txt
    ansible-galaxy install -r dependencies.yml
}

prepare_secrets() {
    echo "============================================= Prepare secrets ==============================================="
    mkdir -p secrets
    cp -r vaults/* secrets/
    ansible-vault decrypt secrets/*
}


install_basic_packages
setup_venv
prepare_secrets
